- hosts: all
  become: true
  tasks:
    - name: Copy pcap file from control node
      fetch:
        src: /home/marco/Desktop/pcaps.pcap
        dest: /home/marco/CPE243H8/
        flat: yes

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Create directory for executable file
      file:
        path: /home/marco/CPE243H8/report.xml
        state: directory

    - name: Extract executable file
      command: tcpflow -r /home/marco/CPE243H8/pcaps.pcap -o /home/marco/CPE243H8/
      args:
        creates: cat /home/marco/CPE243H8/report.xml


    - name: Debug.exe file
      command: cat /home/marco/CPE243H8/report.xml
      register: cat_output
      changed_when: false

    - debug:
        var: cat_output.stdout_lines
