---
- name: Collect and extract executable from PCAP file
  hosts: control-node
  gather_facts: no
  vars:
    pcap_file: "~CPE243H8/pcap/file.pcap"
    executable_name: "MARCO"
  tasks:
    - name: Install required packages
      apt:
        name: tcpdump
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      yum:
        name: tcpdump
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Copy PCAP file to managed node
      copy:
        src: "~CPE243H8/pcap/file.pcap"
        dest: "/tmp/MARCO"
        mode: 0644

    - name: Extract executable from PCAP file
      command: tshark -r "/tmp/MARCO" -Y "http.file_data" -T fields -e http.file_data > "/tmp/MARCO.bin"
      args:
        creates: "/tmp/MARCO.bin"

    - name: Change file permissions
      file:
        path: "/tmp/MARCO.bin"
        mode: 0755
        state: file

    - name: Transfer executable to managed node
      copy:
        src: "/tmP/MARCO.bin"
        dest: "~CPE243H8/pcap/file.pcap"
        mode: 0755



TASK [Extract executable file] ******************************************************************
fatal: [192.168.56.107]: FAILED! => {"changed": true, "cmd": ["tcpflow", "-r", "/home/marco/CPE243H8/pcaps.pcap", "-o", "/home/marco/CPE243H8/report.xml"], "delta": "0:00:00.030932", "end": "2024-03-19 03:47:45.536496", "msg": "non-zero return code", "rc": 1, "start": "2024-03-19 03:47:45.505564", "stderr": "reportfilename: /home/marco/CPE243H8/report.xml/report.xml\ntcpflow: /home/marco/CPE243H8/pcaps.pcap: No such file or directory", "stderr_lines": ["reportfilename: /home/marco/CPE243H8/report.xml/report.xml", "tcpflow: /home/marco/CPE243H8/pcaps.pcap: No such file or directory"], "stdout": "", "stdout_lines": []}


